general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on
}


# Lock the screen
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off the screen faster when locked
listener {
    timeout = 30
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

